import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";
import WhatsAppButton from "./_components/WhatsappButton";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Modern hotel website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="tr"
      className={`bg-cover bg-center bg-no-repeat ${inter.className}`}
      style={{ backgroundImage: "url('/hero-background.jpg')" }}
    >
      <body>
        <div className="min-h-screen ">
          <Navbar />
          {children}
          <WhatsAppButton />
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
