import type { Metadata } from "next";
import "./globals.css";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";

import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Modern hotel website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="tr"
      className={`bg-cover bg-center bg-no-repeat ${inter.className}`}
      style={{ backgroundImage: "url('/hero-background.jpg')" }}
    >
      <body>
        <div className="min-h-screen mb-20">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
