import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";
import WhatsAppButton from "./_components/WhatsappButton";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Modern hotel website",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html
      lang={locale}
      className={`bg-cover bg-center bg-no-repeat ${inter.className}`}
      style={{ backgroundImage: "url('/hero-background.jpg')" }}
    >
      <body>
        <NextIntlClientProvider>
          <div className="min-h-screen ">
            <Navbar />
            {children}
            <WhatsAppButton />
          </div>
          <Footer />
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
